baseURL = "https://localstatic.com/"
languageCode = "en-us"
title = "localstatic"
theme = "hermit"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/localstatic"

[[params.social]]
  name = "github"
  url = "https://github.com/localstatic"
